#                                                                        #
# Settings for the Production context                                    #
#                                                                        #

Neos:
  Neos:
    typoScript:
      enableObjectTreeCache: true
